# Generated by Django 5.2.4 on 2025-07-18 08:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('flood', 'Flood'), ('drought', 'Drought')], max_length=10)),
                ('forecast_period', models.IntegerField(choices=[(0, 'Current Day'), (7, '7 Days Ahead'), (14, '14 Days Ahead'), (21, '21 Days Ahead')])),
                ('prediction_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gee_image_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tile_url', models.URLField(blank=True, null=True)),
                ('affected_area_km2', models.FloatField(blank=True, null=True)),
                ('severity_level', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('prediction_type', 'forecast_period', 'prediction_date')},
            },
        ),
        migrations.CreateModel(
            name='PredictionMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('data_sources', models.TextField(blank=True, null=True)),
                ('color_palette', models.CharField(blank=True, max_length=100, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='dashboard.prediction')),
            ],
        ),
    ]
